# Generated by Django 5.0.3 on 2024-03-29 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Track",
            new_name="MusicTrack",
        ),
    ]
